version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
